import { renderProductPhase2AppHtml } from "./product-phase2-app.js";
import { PRODUCT_TITLE } from "./brand.js";

const phase4Script = `<script>
(() => {
  const root = window.__niubigeoPhase2;
  if (!root) return;
  const state = root.state;
  state.phase4 = { loading:false, action:"idle", reports:[], report:null, error:"", modelFilter:"all", evidence:null, competitorId:"" };
  const phase = state.phase4;
  const safeLink = (value) => { try { const parsed = new URL(value); return parsed.protocol === "https:" || parsed.protocol === "http:" ? parsed.toString() : ""; } catch { return ""; } };
  const statusText = (value) => value === "recognized" ? "本次明确表示认识" : value === "partially_recognized" ? "本次部分识别" : value === "unknown" ? "本次无法确认" : value === "ambiguous" ? "本次识别存在歧义" : value === "not_recognized" ? "本次明确表示不认识" : value === "analysis_failed" ? "已收到回答，整理失败" : value === "provider_failed" ? "本次请求失败" : value === "unsupported" ? "当前模型或执行方式不支持" : "证据完整性错误";
  const fieldText = (value) => value === "reported" ? "已列出" : value === "not_reported" ? "本次未列出" : value === "analysis_failed" ? "整理失败" : value === "provider_failed" ? "请求失败" : value === "unsupported" ? "不支持" : value === "entity_unresolved" ? "身份未确认" : "无法确认";
  const tag = (value) => '<span class="tag ' + (value === "recognized" ? "ready" : value === "provider_failed" || value === "analysis_failed" || value === "evidence_integrity_error" ? "warning" : "") + '">' + root.html(statusText(value)) + '</span>';
  const selectedProject = () => root.project();
  const run = () => state.recognitionDetail && state.recognitionDetail.run ? state.recognitionDetail.run : null;
  const reportPath = () => { const selected = selectedProject(); const selectedRun = run(); return selected && selectedRun ? "/api/projects/" + encodeURIComponent(selected.id) + "/recognition-runs/" + encodeURIComponent(selectedRun.id) + "/reports" : ""; };
  const modelFor = (modelRunId) => phase.report ? phase.report.models.find((model) => model.modelRunId === modelRunId) || null : null;
  const allowedLink = (url, label) => { const safe = safeLink(url); return safe ? '<a href="' + root.html(safe) + '" target="_blank" rel="noreferrer noopener">' + root.html(label) + '</a>' : '<span class="subtle">不安全链接已隐藏</span>'; };
  const evidenceHtml = (model, evidence, label) => {
    if (!evidence || evidence.integrity !== "valid" || !model.rawAnswer) return '<span class="subtle">没有可定位的证据片段</span>';
    return '<button type="button" class="evidence-jump" data-phase4-evidence-model="' + root.html(model.modelRunId) + '" data-phase4-evidence-start="' + evidence.evidence.start + '" data-phase4-evidence-end="' + evidence.evidence.end + '">' + root.html(label || "查看证据") + '</button>';
  };
  const renderRaw = (model) => {
    if (!model || !model.rawAnswer) return '<p class="subtle">这个模型没有可展示的原始回答。</p>';
    const evidence = phase.evidence && phase.evidence.modelRunId === model.modelRunId ? phase.evidence : null;
    if (!evidence) return '<pre class="raw-answer" data-testid="report-raw-answer">' + root.html(model.rawAnswer) + '</pre>';
    const answer = model.rawAnswer;
    const start = evidence.start;
    const end = evidence.end;
    if (start < 0 || end < start || end > answer.length) return '<pre class="raw-answer" data-testid="report-raw-answer">' + root.html(answer) + '</pre>';
    return '<pre class="raw-answer" data-testid="report-raw-answer">' + root.html(answer.slice(0, start)) + '<mark>' + root.html(answer.slice(start, end)) + '</mark>' + root.html(answer.slice(end)) + '</pre>';
  };
  const field = (title, claim, model) => '<div class="detail-cell"><span>' + root.html(title) + '</span><strong>' + root.html(claim && claim.value ? claim.value : "无法确认") + '</strong>' + (claim ? evidenceHtml(model, claim.evidence, "查看证据") : "") + '</div>';
  const reportModelCard = (model) => {
    const unavailable = model.state === "analysis_failed" || model.state === "provider_failed" || model.state === "unsupported" || model.state === "evidence_integrity_error";
    const competitors = model.competitors === null ? '<p class="subtle">竞品字段无法整理，不能解释为空。</p>' : model.competitors.length ? '<ul>' + model.competitors.map((item) => '<li><strong>' + root.html(item.name) + '</strong>' + (item.domain ? ' · ' + root.html(item.domain) : ' · 身份未确认') + ' ' + evidenceHtml(model, item.evidence, "证据") + '</li>').join("") + '</ul>' : '<p class="subtle">本次未列出竞争对象。</p>';
    const keywords = model.brandKeywords === null ? '<p class="subtle">关键词字段无法整理。</p>' : model.brandKeywords.length ? '<div class="inline-actions">' + model.brandKeywords.map((item) => '<span class="tag">' + root.html(item.keyword) + '</span>' + evidenceHtml(model, item.evidence, "证据")).join("") + '</div>' : '<p class="subtle">本次未返回目标品牌关键词。</p>';
    const retry = model.state === "analysis_failed" || model.state === "provider_failed" || model.state === "unsupported" ? '<button type="button" class="card-action" data-phase4-retry-model="' + root.html(model.modelRunId) + '">单独重试</button>' : "";
    return '<article class="model-run-card" data-testid="report-model-card"><div class="model-run-head"><div><h3>' + root.html(model.displayName) + '</h3><p class="subtle">' + root.html(model.modelId) + ' · ' + root.html(model.webSearch.label) + '</p></div><div class="inline-actions">' + tag(model.state) + retry + '</div></div>' + (unavailable ? '<div class="warning-box">' + root.html(model.unavailableReason || "该模型没有可用于报告的结构化结果。") + '</div>' : '<div class="detail-grid">' + field("模型识别的品牌", model.recognizedBrand, model) + field("业务描述", model.businessDescription, model) + field("产品类别", model.productCategory, model) + '</div>') + '<div class="evidence-group"><h4>竞争对象</h4>' + competitors + '</div><div class="evidence-group"><h4>目标品牌关键词</h4>' + keywords + '</div><details class="evidence-details"><summary>查看原始回答与技术证据</summary><div class="evidence-group"><h4>原始回答</h4>' + renderRaw(model) + '</div><div class="evidence-group"><h4>Provider 原始响应</h4><pre class="raw-answer">' + root.html(JSON.stringify(model.rawProviderResponse, null, 2)) + '</pre></div></details></article>';
  };
  const cell = (row, model) => { const entry = row.cells.find((item) => item.modelRunId === model.modelRunId); if (!entry) return '<td>无法确认</td>'; const record = entry.recordIds.length ? ' <button type="button" class="evidence-jump" data-phase4-record="' + root.html(entry.recordIds[0]) + '">查看证据</button>' : ""; return '<td data-testid="report-matrix-cell">' + root.html(fieldText(entry.state)) + record + '</td>'; };
  const matrix = (title, rows, models, kind) => rows.length ? '<section class="section-card"><div class="section-head"><div><h2>' + root.html(title) + '</h2><p class="subtle">每一格只表示该模型本次是否返回对应记录，不代表市场事实。</p></div></div><div class="matrix-wrap"><table class="matrix" data-testid="report-' + root.html(kind) + '-matrix"><thead><tr><th>对象</th>' + models.map((model) => '<th>' + root.html(model.displayName) + '</th>').join("") + '</tr></thead><tbody>' + rows.map((row) => '<tr><th>' + root.html(row.name || row.keyword) + (row.host ? '<span class="subtle">' + root.html(row.host) + '</span>' : "") + '</th>' + models.map((model) => cell(row, model)).join("") + '</tr>').join("") + '</tbody></table></div></section>' : '<section class="section-card"><h2>' + root.html(title) + '</h2><p class="subtle">本次没有可展示的记录。</p></section>';
  const competitorKeywords = (report, models) => {
    const group = report.competitorGroups.find((item) => item.id === phase.competitorId) || report.competitorGroups[0] || null;
    if (!group) return '<section class="section-card"><h2>竞争对象关键词</h2><p class="subtle">本次没有竞争对象关键词。</p></section>';
    const options = report.competitorGroups.map((item) => '<option value="' + root.html(item.id) + '">' + root.html(item.name + (item.host ? " · " + item.host : " · 身份未确认")) + '</option>').join("");
    const rows = [];
    for (const model of models) {
      const records = model.competitors || [];
      const groupRecordIds = new Set(group.sourceRecordIds);
      const selected = records.filter((record) => groupRecordIds.has(record.id));
      for (const record of selected) {
        const values = (model.competitorKeywords || []).filter((keyword) => keyword.competitorRecordId === record.id);
        for (const value of values) rows.push({ model, value, record });
      }
    }
    return '<section class="section-card"><div class="section-head"><div><h2>竞争对象关键词</h2><p class="subtle">关键词只属于对应的原始竞争对象记录，不会跨对象共享。</p></div><select id="report-competitor-select" data-testid="report-competitor-select">' + options + '</select></div><div class="detail-grid">' + (rows.length ? rows.map((row) => '<div class="detail-cell"><span>' + root.html(row.model.displayName) + ' · ' + root.html(row.record.name) + '</span><strong>' + root.html(row.value.keyword) + '</strong>' + evidenceHtml(row.model, row.value.evidence, "查看证据") + '</div>').join("") : '<p class="subtle">该对象本次没有可展示的关键词。</p>') + '</div></section>';
  };
  const sources = (models) => '<section class="section-card"><div class="section-head"><div><h2>来源</h2><p class="subtle">Provider Citation 与回答正文中的 URL 分开保存和展示。</p></div></div><div class="source-columns"><div><h3>Provider Citation</h3>' + models.map((model) => { const values = model.providerCitations; return '<div class="evidence-group"><strong>' + root.html(model.displayName) + '</strong>' + (values === null ? '<p class="subtle">无法整理</p>' : values.length ? '<ul>' + values.map((item) => '<li>' + allowedLink(item.url, item.title || item.domain) + '<span class="subtle"> · ' + root.html(item.providerPayloadPath) + '</span></li>').join("") + '</ul>' : '<p class="subtle">本次未返回 Provider Citation。</p>') + '</div>'; }).join("") + '</div><div><h3>回答正文 URL</h3>' + models.map((model) => { const values = model.answerMentionedUrls; return '<div class="evidence-group"><strong>' + root.html(model.displayName) + '</strong>' + (values === null ? '<p class="subtle">无法整理</p>' : values.length ? '<ul>' + values.map((item) => '<li>' + allowedLink(item.url, item.domain) + ' ' + evidenceHtml(model, item.evidence, "证据") + '</li>').join("") + '</ul>' : '<p class="subtle">本次没有普通 URL。</p>') + '</div>'; }).join("") + '</div></div></section>';
  const reportBody = () => {
    const report = phase.report;
    const selected = selectedProject();
    if (!selected) return '<section class="view"><div class="empty"><div class="empty-copy"><h2>先选择项目</h2></div></div></section>';
    if (phase.loading) return '<section class="view"><div class="empty"><div class="empty-copy"><h2>正在读取当前报告</h2><p class="subtle">不会重新调用模型。</p></div></div></section>';
    if (phase.error) return '<section class="view"><div class="warning-box"><strong>无法准备报告</strong><p>' + root.html(phase.error) + '</p><button type="button" class="button" data-phase4-retry>重新读取</button></div></section>';
    if (!report) return '<section class="view"><div class="empty"><div class="empty-copy"><h2>还没有可展示的认知报告</h2><p class="subtle">完成一次认知测试后，系统会基于固定的本次证据生成报告。</p></div></div></section>';
    const models = phase.modelFilter === "all" ? report.models : report.models.filter((model) => model.modelRunId === phase.modelFilter);
    const filters = '<button type="button" class="filter ' + (phase.modelFilter === "all" ? "active" : "") + '" data-phase4-model="all">全部模型</button>' + report.models.map((model) => '<button type="button" class="filter ' + (phase.modelFilter === model.modelRunId ? "active" : "") + '" data-phase4-model="' + root.html(model.modelRunId) + '">' + root.html(model.displayName) + '</button>').join("");
    const history = phase.reports.length > 1 ? '<select id="report-history" data-testid="report-history">' + phase.reports.map((item) => '<option value="' + root.html(item.reportId) + '" ' + (item.reportId === report.reportId ? "selected" : "") + '>报告版本 ' + item.reportRevision + ' · ' + root.html(root.formatTime(item.generatedAt)) + '</option>').join("") + '</select>' : '<span class="subtle">报告版本 ' + report.reportRevision + '</span>';
    const off = models.filter((model) => model.recognitionMode === "unaided_domain_recognition");
    const web = models.filter((model) => model.recognitionMode === "native_web_domain_discovery");
    const modelSummary = '<div class="detail-grid"><div class="detail-cell"><span>模型数</span><strong>' + report.models.length + '</strong></div><div class="detail-cell"><span>成功整理</span><strong>' + report.models.filter((model) => model.state !== "analysis_failed" && model.state !== "provider_failed" && model.state !== "unsupported" && model.state !== "evidence_integrity_error").length + '</strong></div><div class="detail-cell"><span>整理失败</span><strong>' + report.models.filter((model) => model.state === "analysis_failed").length + '</strong></div><div class="detail-cell"><span>请求失败</span><strong>' + report.models.filter((model) => model.state === "provider_failed").length + '</strong></div></div>';
    return '<section class="view" data-testid="recognition-report"><div class="heading"><div><h1>当前认知报告</h1><p class="subtle">' + root.html(report.domain) + ' · ' + root.html(root.formatTime(report.generatedAt)) + ' · 监测配置v' + report.monitoringConfigurationVersion + '</p></div><div class="inline-actions">' + history + '<button type="button" class="button" data-phase4-refresh data-testid="refresh-report">刷新报告</button></div></div><div class="section-stack">' + modelSummary + '<section class="section-card"><div class="section-head"><div><h2>模型认知</h2><p class="subtle">模型的描述只代表本次回答。离线认知与实际联网发现分开显示。</p></div></div><div class="toolbar">' + filters + '</div><h3>不联网域名认知</h3><div class="model-run-list">' + (off.length ? off.map(reportModelCard).join("") : '<p class="subtle">当前筛选没有不联网模型。</p>') + '</div><h3>Provider 原生联网发现</h3><div class="model-run-list">' + (web.length ? web.map(reportModelCard).join("") : '<p class="subtle">当前筛选没有联网模型。</p>') + '</div></section>' + matrix("竞争对象", report.competitorGroups, models, "competitor") + matrix("目标品牌关键词", report.brandKeywordGroups, models, "keyword") + competitorKeywords(report, models) + sources(models) + '<section class="section-card"><h2>技术详情</h2><details><summary>查看固定来源与协议</summary><pre class="raw-answer">' + root.html(JSON.stringify({ reportId:report.reportId, sourceAttemptMap:report.sourceAttemptMap, sourceRecordHashes:report.sourceRecordHashes, protocol:report.protocol, sourceFingerprint:report.sourceFingerprint }, null, 2)) + '</pre></details></section></div></section>';
  };
  const shell = () => { const selected = selectedProject(); const options = state.currentProjects.length ? state.currentProjects.map((item) => '<option value="' + root.html(item.id) + '">' + root.html(item.name) + ' · ' + root.html(item.normalizedDomain) + '</option>').join("") : '<option value="">还没有项目</option>'; root.app.innerHTML = '<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-lockup">' + root.brandLockup + '</div></div><div class="project-label">项目</div><select id="project-select" class="project-select" aria-label="项目切换" data-testid="project-select">' + options + '</select><nav class="nav" aria-label="项目导航"><button type="button" class="nav-item" data-page="overview">总览</button><button type="button" class="nav-item" data-page="models">AI 模型</button><button type="button" class="nav-item" data-page="configuration">监测配置</button><button type="button" class="nav-item" data-page="recognition">域名认知</button><button type="button" class="nav-item active" data-page="reports">当前报告</button><button type="button" class="nav-item" data-phase5-open>持续测量</button></nav><div class="sidebar-bottom">当前报告</div></aside><main class="workspace"><header class="topbar"><div class="crumb"><strong>${PRODUCT_TITLE}</strong> / ' + root.html(selected ? selected.name : "项目") + '</div><button id="new-project" type="button" class="button primary" data-testid="new-project">新建项目</button></header><section class="content">' + reportBody() + '</section></main></div>'; const select = root.element("project-select"); if (select) select.value = state.selectedId; };
  const loadReport = async (reportId) => { const path = reportPath(); if (!path) { phase.report = null; return; } const response = await root.request(path + "/" + encodeURIComponent(reportId)); phase.report = response.report; phase.competitorId = phase.competitorId || (phase.report.competitorGroups[0] ? phase.report.competitorGroups[0].id : ""); };
  const open = async () => { phase.loading = true; phase.error = ""; shell(); try { await root.refreshRecognition(); const path = reportPath(); if (!path) { phase.reports = []; phase.report = null; return; } const listed = await root.request(path); const created = await root.request(path, { method:"POST" }); const known = listed.reports || []; phase.reports = known.some((item) => item.reportId === created.report.reportId) ? known : [...known, created.report]; phase.reports.sort((left, right) => left.reportRevision - right.reportRevision); phase.report = created.report; phase.action = "idle"; } catch (error) { phase.error = error instanceof Error ? error.message : "请求未完成"; } finally { phase.loading = false; shell(); } };
  const findEvidence = (recordId) => { if (!phase.report) return null; for (const model of phase.report.models) { const competitor = (model.competitors || []).find((item) => item.id === recordId); if (competitor && competitor.evidence.integrity === "valid") return { modelRunId:model.modelRunId, start:competitor.evidence.evidence.start, end:competitor.evidence.evidence.end }; const brand = (model.brandKeywords || []).find((item) => item.id === recordId); if (brand && brand.evidence.integrity === "valid") return { modelRunId:model.modelRunId, start:brand.evidence.evidence.start, end:brand.evidence.evidence.end }; } return null; };
  window.__niubigeoPhase4 = { render:shell, open };
  document.addEventListener("click", async (event) => { const target = event.target; if (!(target instanceof Element)) return; const measurement = target.closest("[data-phase5-open]"); if (measurement) { const next = new URL(window.location.href); const selected = selectedProject(); next.searchParams.set("view", "measurements"); if (selected) next.searchParams.set("project", selected.id); window.location.assign(next.toString()); return; } const filter = target.closest("[data-phase4-model]"); if (filter) { phase.modelFilter = filter.getAttribute("data-phase4-model") || "all"; shell(); return; } if (target.closest("[data-phase4-refresh]") || target.closest("[data-phase4-retry]")) { if (!phase.loading) await open(); return; } const retryModel = target.closest("[data-phase4-retry-model]"); if (retryModel) { const selected = selectedProject(); const selectedRun = run(); const runId = phase.report ? phase.report.runId : selectedRun ? selectedRun.id : ""; const modelRunId = retryModel.getAttribute("data-phase4-retry-model"); if (!selected || !runId || !modelRunId || phase.action === "loading") return; phase.action = "loading"; retryModel.setAttribute("data-action-state", "loading"); retryModel.textContent = "正在重试…"; try { await root.request("/api/projects/" + encodeURIComponent(selected.id) + "/recognition-runs/" + encodeURIComponent(runId) + "/model-runs/" + encodeURIComponent(modelRunId) + "/retry", { method:"POST" }); state.recognitionSelectedRunId = runId; await root.refreshRecognition(); await open(); } catch (error) { phase.error = error instanceof Error ? error.message : "重试失败"; shell(); } finally { phase.action = "idle"; } return; } const evidence = target.closest("[data-phase4-evidence-model]"); if (evidence) { phase.evidence = { modelRunId:evidence.getAttribute("data-phase4-evidence-model") || "", start:Number(evidence.getAttribute("data-phase4-evidence-start")), end:Number(evidence.getAttribute("data-phase4-evidence-end")) }; shell(); const raw = document.querySelector("[data-testid=report-raw-answer] mark"); if (raw) raw.scrollIntoView({ block:"center", behavior:"smooth" }); return; } const record = target.closest("[data-phase4-record]"); if (record) { phase.evidence = findEvidence(record.getAttribute("data-phase4-record") || ""); shell(); return; } });
  document.addEventListener("change", async (event) => { const target = event.target; if (!(target instanceof HTMLSelectElement)) return; if (target.id === "report-history") { await loadReport(target.value); shell(); return; } if (target.id === "report-competitor-select") { phase.competitorId = target.value; shell(); } });
})();
</script>`;

export function renderProductPhase4AppHtml(): string {
  return renderProductPhase2AppHtml().replace("</body>", `${phase4Script}</body>`);
}
